### ISSUE TITLE
Filter is not working?

### ISSUE THREAD

**Issue by iwasherefirst2** [flathunters/flathunter#151]
Hey, the filtering for excluded titles does not seem to work.

This is my configuration:

```
#
# Example:
# filters:
#   excluded_titles:
#     - "wg"
#     - "zwischenmiete"
#   min_price: 700
#   max_price: 1000
#   min_size: 50
#   max_size: 80
#   max_price_per_square: 1000
filters:
  excluded_titles:
    - "zwischenmiete"
    - "tauschwohnung"
    - "suche"
    - "gesucht"
    - "TAUSCH"
    - "auf Zeit"       
  max_price: 1800 
  
# There are often city districts in the address which
# Google Maps does not like. Use this blacklist to remove
# districts from the search.
blacklist:
        #  - Innenstadt

```

I then run the command for this url: https://www.ebay-kleinanzeigen.de/s-wohnung-mieten/berlin/c203l3331+wohnung_mieten.qm_d:90%2C+wohnung_mieten.zimmer_d:4%2C

and I received results with the title as follows:

- "NUR TAUSCH WOHNUNG. 3z-->4z" 
- "Wohnung auf Zeit, möbiliert"
- "NUR TAUSCH 5 1/2 ..."
- "4,5 Zimmer wohnung zum tausch ...."
- "Tausch: 4 Zi Whg Zehlendorf ..."

Shouldn't all of them be filtered?
