### ISSUE TITLE
Dependabot integration

### ISSUE THREAD

**Issue by veldhaenchen** [flathunters/flathunter#224]
It would be great if there is a integration with the dependabot making sure this project runs on latest versions of the dependencies.
The Codeowner can setup this inside the settings tab.

for example you can use this inside ./github/dependabot.yml

```
version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    target-branch: "main"

```
