### ISSUE TITLE
"NoneType" in title_el.get("href") when scraping kleinanzeigen 

### ISSUE THREAD

**Issue by alvarnydev** [flathunters/flathunter#515]
Hi you lovely people! 

I currently run into an issue when scraping kleinanzeigen because the bot seems to have trouble getting the link from the current listing it parses over, sometimes. It works for a while and eventually breaks. Looks like this for me:

<img width="1161" alt="Screenshot 2024-01-17 at 13 06 53" src="https://github.com/flathunters/flathunter/assets/100701133/ccbae79a-70f5-4cfe-9394-2887806d31da">

  
  

I looked through the existing and past issues and didn't find anything similar. Nevertheless, have you guys maybe seen this before? I run the Docker image of flathunter using docker compose on an Ubuntu 22 machine with the following config:
```
wghunter:
    build: .
    platform: linux/amd64
    command: python flathunt.py
    restart: always
    environment:
      - FLATHUNTER_TARGET_URLS=https://www.kleinanzeigen.de/s-frankfurt-am-main/wg/k0l4292;https://www.wg-gesucht.de/wg-zimmer-in-Frankfurt-am-Main.41.0.1.0.html?csrf_token=bf76f1e4c7392fd9aeadc109872a8fb14038151b&offer_filter=1&city_id=41&sort_order=0&noDeact=1&categories%5B%5D=0&rMax=1000&wgMxT=3&wgAge=28&wgSmo=2&exc=2&img_only=1
      - FLATHUNTER_DATABASE_LOCATION=./dbs/wgs/
      - FLATHUNTER_LOOP_PERIOD_SECONDS=120
      - FLATHUNTER_MESSAGE_FORMAT={title} \#CR# > Zimmer {rooms} \#CR# > Größe {size} \#CR# > Preis {price} \#CR# > Ort {address} \#CR# > Link {url}
      - FLATHUNTER_NOTIFIERS=telegram
      - FLATHUNTER_TELEGRAM_BOT_TOKEN=<...>
      - FLATHUNTER_TELEGRAM_RECEIVER_IDS=<...>
      - FLATHUNTER_HEADLESS_BROWSER=yes
    volumes:
      - ./:/usr/src/app
```
