### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by amy1337** [flathunters/flathunter#538]
Good afternoon,

I'm currently having some issues while running the bot. When attempting to execute the command sudo docker-compose up, I encountered the following error:

```
[nix-shell:~/flathunter]$ sudo docker-compose up
[+] Running 1/0
 ✔ Container flathunter-app-1  Created                                                                                                                                                   0.0s 
Attaching to flathunter-app-1
flathunter-app-1  | [2024/02/17 01:30:28|logging.py              |DEBUG   ]: Settings from config: {"captcha_enabled": false, "captcha_driver_arguments": ["--no-sandbox", "--headless", "--disable-gpu", "--remote-debugging-port=9222", "--disable-dev-shm-usage", "--window-size=1024,768"], "captcha_solver": "NoneType", "imagetyperz_token": null, "twocaptcha_key": null, "mattermost_webhook_url": null, "notifiers": ["telegram"], "slack_webhook_url": "", "telegram_receiver_ids": [XXXX, XXXX], "telegram_bot_token": "694xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxFPs", "target_urls": ["https://www.kleinanzeigen.de/s-wohnung-mieten/berlin/anzeige:angebote/preis:200:1200/c203l3331+wohnung_mieten.swap_s:nein+wohnung_mieten.zimmer_d:2%2C"], "use_proxy": false}
flathunter-app-1  | [2024/02/17 01:30:28|abstract_crawler.py     |DEBUG   ]: Got search URL https://www.kleinanzeigen.de/s-wohnung-mieten/berlin/anzeige:angebote/preis:200:1200/c203l3331+wohnung_mieten.swap_s:nein+wohnung_mieten.zimmer_d:2%2C
flathunter-app-1  | [2024/02/17 01:30:28|chrome_wrapper.py       |INFO    ]: Initializing Chrome WebDriver for crawler...
flathunter-app-1  | Traceback (most recent call last):
flathunter-app-1  |   File "/usr/src/app/flathunt.py", line 99, in <module>
flathunter-app-1  |     main()
flathunter-app-1  |   File "/usr/src/app/flathunt.py", line 95, in main
flathunter-app-1  |     launch_flat_hunt(config, heartbeat)
flathunter-app-1  |   File "/usr/src/app/flathunt.py", line 35, in launch_flat_hunt
flathunter-app-1  |     hunter.hunt_flats()
flathunter-app-1  |   File "/usr/src/app/flathunter/hunter.py", line 56, in hunt_flats
flathunter-app-1  |     for expose in processor_chain.process(self.crawl_for_exposes(max_pages)):
flathunter-app-1  |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flathunter-app-1  |   File "/usr/src/app/flathunter/hunter.py", line 35, in crawl_for_exposes
flathunter-app-1  |     return chain(*[try_crawl(searcher, url, max_pages)
flathunter-app-1  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flathunter-app-1  |   File "/usr/src/app/flathunter/hunter.py", line 35, in <listcomp>
flathunter-app-1  |     return chain(*[try_crawl(searcher, url, max_pages)
flathunter-app-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flathunter-app-1  |   File "/usr/src/app/flathunter/hunter.py", line 27, in try_crawl
flathunter-app-1  |     return searcher.crawl(url, max_pages)
flathunter-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flathunter-app-1  |   File "/usr/src/app/flathunter/abstract_crawler.py", line 151, in crawl
flathunter-app-1  |     return self.get_results(url, max_pages)
flathunter-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flathunter-app-1  |   File "/usr/src/app/flathunter/abstract_crawler.py", line 139, in get_results
flathunter-app-1  |     soup = self.get_page(search_url)
flathunter-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
flathunter-app-1  |   File "/usr/src/app/flathunter/crawler/kleinanzeigen.py", line 56, in get_page
flathunter-app-1  |     return self.get_soup_from_url(search_url, driver=self.get_driver())
flathunter-app-1  |                                                      ^^^^^^^^^^^^^^^^^
flathunter-app-1  |   File "/usr/src/app/flathunter/crawler/kleinanzeigen.py", line 44, in get_driver
flathunter-app-1  |     self.driver = get_chrome_driver(driver_arguments)
flathunter-app-1  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flathunter-app-1  |   File "/usr/src/app/flathunter/chrome_wrapper.py", line 69, in get_chrome_driver
flathunter-app-1  |     driver = uc.Chrome(version_main=chrome_version, options=chrome_options) # pylint: disable=no-member
flathunter-app-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flathunter-app-1  |   File "/usr/local/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 258, in __init__
flathunter-app-1  |     self.patcher.auto()
flathunter-app-1  |   File "/usr/local/lib/python3.11/site-packages/undetected_chromedriver/patcher.py", line 178, in auto
flathunter-app-1  |     self.unzip_package(self.fetch_package())
flathunter-app-1  |                        ^^^^^^^^^^^^^^^^^^^^
flathunter-app-1  |   File "/usr/local/lib/python3.11/site-packages/undetected_chromedriver/patcher.py", line 287, in fetch_package
flathunter-app-1  |     return urlretrieve(download_url)[0]
flathunter-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
flathunter-app-1  |   File "/usr/local/lib/python3.11/urllib/request.py", line 241, in urlretrieve
flathunter-app-1  |     with contextlib.closing(urlopen(url, data)) as fp:
flathunter-app-1  |                             ^^^^^^^^^^^^^^^^^^
flathunter-app-1  |   File "/usr/local/lib/python3.11/urllib/request.py", line 216, in urlopen
flathunter-app-1  |     return opener.open(url, data, timeout)
flathunter-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flathunter-app-1  |   File "/usr/local/lib/python3.11/urllib/request.py", line 525, in open
flathunter-app-1  |     response = meth(req, response)
flathunter-app-1  |                ^^^^^^^^^^^^^^^^^^^
flathunter-app-1  |   File "/usr/local/lib/python3.11/urllib/request.py", line 634, in http_response
flathunter-app-1  |     response = self.parent.error(
flathunter-app-1  |                ^^^^^^^^^^^^^^^^^^
flathunter-app-1  |   File "/usr/local/lib/python3.11/urllib/request.py", line 563, in error
flathunter-app-1  |     return self._call_chain(*args)
flathunter-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^
flathunter-app-1  |   File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
flathunter-app-1  |     result = func(*args)
flathunter-app-1  |              ^^^^^^^^^^^
flathunter-app-1  |   File "/usr/local/lib/python3.11/urllib/request.py", line 643, in http_error_default
flathunter-app-1  |     raise HTTPError(req.full_url, code, msg, hdrs, fp)
flathunter-app-1  | urllib.error.HTTPError: HTTP Error 404: Not Found
flathunter-app-1  | [2024/02/17 01:30:29|__init__.py             |INFO    ]: ensuring close
flathunter-app-1 exited with code 0`

```
For the bot, I use the following config:

```
version: '3'

services:
  app:
    build: .
    platform: linux/amd64 # For M1 to install google-chrome-stable; However still crashes on M1 when launching chrome (selenium.common.exceptions.WebDriverException: Message: unknown error: unable to discover open window in chrome (Session info: headless chrome=109.0.5414.119))
    command: python flathunt.py
    restart: always
    environment:
      - FLATHUNTER_TARGET_URLS=https://www.kleinanzeigen.de/s-wohnung-mieten/berlin/anzeige:angebote/preis:200:1200/c203l3331+wohnung_mieten.swap_s:nein+wohnung_mieten.zimmer_d:2%2C
      - FLATHUNTER_VERBOSE_LOG=/tmp/flathunter.log
      - FLATHUNTER_LOOP_PERIOD_SECONDS=600
      # - FLATHUNTER_MESSAGE_FORMAT=
      - FLATHUNTER_NOTIFIERS=telegram
      - FLATHUNTER_TELEGRAM_BOT_TOKEN=XXXXX
      - FLATHUNTER_TELEGRAM_RECEIVER_IDS=XXXX,XXXX
      - FLATHUNTER_2CAPTCHA_KEY=XXXXXX
      # - FLATHUNTER_IMAGETYPERZ_TOKEN=
      - FLATHUNTER_HEADLESS_BROWSER=yes
    volumes:
      - ./:/usr/src/app # not ideal, but the only way to incorporate the database (processed_ids.db), which is currently created at runtime

```

Might this issue be related to the configuration or the environment setup. Could you please assist me in resolving this?

Let me know if you need any further information. Thank you in advance for your help!
