### ISSUE TITLE
Current state of solving `IS24 bot detection has identified our script as a bot - we've been blocked`

### ISSUE THREAD

**Issue by robertszooba** [flathunters/flathunter#589]
This is not the first issue regarding this error. However, browsing through various threads, I am unable to abstract a specific step-by-step guide to solve this problem. Therefore, I would like to ask what needs to be done to circumvent the bot detection.
The relevant parts of my `config.yaml` are:

```
loop:
  active: yes
  sleeping_time: 600

captcha:
  imagetyperz:
    token: ABC
  driver_arguments:
    - "--headless"

immoscout_cookie: abc
```
