### ISSUE TITLE
Two Bots config help

### ISSUE THREAD

**Issue by noid999** [flathunters/flathunter#66]
Hi,
i am a beginner in programming. At this point everything is working fine but is it possible to configure two different bot´s to message? In my example just the second Bot is sending the messages. How do i have to arrange the lines for two bot support? An example would be great.

```
telegram:
   bot_token: 132xxxxxx:xxxxxxxxxxxxxxxxxxxxxxx
   receiver_ids:
       - 306xxxxx
   bot_token: 122xxxxxxxx-xxxxxxxxxxxxxxxxxxxx
   receiver_ids:
       - 102xxxxx
```
